FROM kibana:8.14.2

USER root

COPY kibana.yml /usr/share/kibana/config/
COPY kibana-setup.sh /usr/local/bin/
# COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/kibana-setup.sh

USER kibana

CMD ["/bin/bash", "-c", "/usr/local/bin/kibana-setup.sh & /usr/local/bin/kibana-docker"]
