FROM alpine:3.18

COPY ./conf/run-mariadb.sh /tmp/mariadb-setup.sh
COPY ./conf/mariadb-server.cnf /tmp/mariadb-server.cnf

EXPOSE 3306

RUN apk update && \
	apk add --no-cache mariadb mariadb-server-utils
RUN chmod +x /tmp/mariadb-setup.sh

ENTRYPOINT [ "sh" ]
CMD ["/tmp/mariadb-setup.sh"]
