FROM alpine:3.18

COPY ./conf/run-mariadb.sh /tmp/mariadb-setup.sh
COPY ./conf/mariadb-server.cnf /tmp/mariadb-server.cnf

EXPOSE 3306

RUN apk update && \
	apk add --no-cache mariadb mariadb-server-utils openrc
RUN chmod +x /tmp/mariadb-setup.sh
# RUN sh /tmp/mariadb-setup.sh
# RUN sh /tmp/mariadb-setup.sh
# RUN sh /tmp/mariadb-setup.sh
# Verify the status of the MariaDB service
# RUN rc-service mariadb status;

# CMD ["/usr/bin/mysqld", "--user=mysql", "--console"]
ENTRYPOINT [ "sh" ]
CMD ["/tmp/mariadb-setup.sh"]
