FROM alpine:3.18

ARG DOMAIN
ENV DOMAIN=$DOMAIN

RUN apk update && \
	apk add nginx && \
	apk add openssl && \
	mkdir -p /etc/ssl/private /etc/ssl/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/ssl/private/nginx.key \
      -out /etc/ssl/certs/nginx.crt \
      -subj "/C=KR/ST=Seoul/L=Seoul/O=42/OU=42/CN=junssong.42.fr" && \
  mkdir /usr/share/nginx/html

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# COPY ./conf/index.html /usr/share/nginx/html/index.html
# RUN envsubst '$DOMAIN' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
