version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: "nginx"
    image: "nginx:1.0"
    pull_policy: never
    ports:
      - "443:443"
    networks:
      - inception_network
    env_file:
      - .env
    restart:  on-failure
    init: true
    volumes:
      - wp:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: "mariadb"
    image: "mariadb:1.0"
    pull_policy: never
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure
    init: true

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    image: "wordpress:1.0"
    pull_policy: never
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    networks:
      - inception_network
    env_file: .env
    restart: on-failure
    init: true

networks:
  inception_network:
    name: inception
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/junssong/data/wp
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/junssong/data/db
