FROM alpine:3.18

RUN apk update && \
    apk add --no-cache nginx openssl && \
    rm -rf /var/cache/apk/*

RUN mkdir -p /etc/ssl/private /etc/ssl/certs && \
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/private/nginx.key \
        -out /etc/ssl/certs/nginx.crt \
        -subj "/C=KR/ST=Seoul/L=Seoul/O=42/OU=42"

RUN mkdir /usr/share/nginx/html

COPY ./conf/default.conf /etc/nginx/http.d/defalut.conf

EXPOSE 443

ENTRYPOINT [ "nginx" ]
CMD ["-g", "daemon off;"]

