FROM alpine:3.18

COPY ./conf/run_wordpress.sh /tmp/run_wordpress.sh

RUN apk update && \
	apk add --no-cache php php-mbstring php-phar php-fpm php-mysqli wget && \
	rm -rf /var/cache/apk/*
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

RUN addgroup nginx \
    && adduser -D -G nginx nginx

COPY ./conf/www.conf /etc/php81/php-fpm.d/www.conf

RUN chmod +x /etc/php81/php-fpm.d/www.conf

EXPOSE 9000

ENTRYPOINT [ "sh" ]
CMD ["/tmp/run_wordpress.sh"]
